-- ============================================================================
-- kArchiveManager 2.0 - SEED of the tested processes (classic SSMS, no SQLCMD).
-- ----------------------------------------------------------------------------
-- Captured from RADIM-STACHAL\RSTSQL2022.kArchiveManagerAdmin. Source databases
-- referenced: AAD / Edge / KMWEBV / KMWE_Test. FK ProcessId is resolved via
-- ProcessCode so this is portable; adjust SourceDb/ArchiveDb names for a customer.
-- Run AFTER the clean object deploy. Idempotent guard: refuses if already seeded.
-- NOTE: WA_AAD_*_OSTRY_SMOKE are TEST fixtures (RetentionDays=1) - disable for prod.
-- ============================================================================
USE [kArchiveManagerAdmin];
GO
SET NOCOUNT ON; SET XACT_ABORT ON;
BEGIN TRAN;

IF EXISTS (SELECT 1 FROM arch.Process WHERE ProcessCode IN (N'INTEGRACE_DNLOAD',N'INTEGRACE_UPLOAD',N'RECEIVING',N'RF_LOG2',N'SHIPPING',N'WA_AAD_PRIJEM_OSTRY_SMOKE',N'WA_AAD_VYDEJ_OSTRY_SMOKE'))
    THROW 60000, 'Seed target processes already exist - delete them first to re-seed.', 1;

-- ---- arch.Process (7 rows) ----
INSERT arch.Process ([ProcessCode], [Description], [IsEnabled], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [CreatedAt], [ModifiedAt], [CutoffMode], [CutoffDate], [DocKeyLabel], [SelectionStrategy], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql]) VALUES (N'RECEIVING', N'KArchiveManager - Purchase Order History', 1, 1, 540, 1440, 500, NULL, 100, 0, 1, NULL, 10000, N'LOW', N'dbo', N'BACKRH', N'PO_NUM', NULL, N'CAST(DATE_CREAT AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', NULL, 0, '2026-05-22T07:31:25.000', '2026-06-02T07:50:04.000', 0, '2024-01-01T00:00:00.000', N'PO_NUM', N'ANCHOR', N'BATCH', 1, NULL, NULL, NULL);
INSERT arch.Process ([ProcessCode], [Description], [IsEnabled], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [CreatedAt], [ModifiedAt], [CutoffMode], [CutoffDate], [DocKeyLabel], [SelectionStrategy], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql]) VALUES (N'SHIPPING', N'KArchiveManager - Sales Order History', 1, 1, 540, 1440, 1000, NULL, 500, 0, 1, NULL, 10000, N'LOW', N'dbo', N'SHIPHIST', N'PACKSLIP', NULL, N'CAST(COALESCE(DATE_UPLD, DATE_SHIP, DATE_CREAT) AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', NULL, 0, '2026-05-22T07:31:25.000', '2026-06-02T07:50:04.000', 0, '2024-01-01T00:00:00.000', N'PACKSLIP', N'ANCHOR', N'BATCH', 1, NULL, NULL, NULL);
INSERT arch.Process ([ProcessCode], [Description], [IsEnabled], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [CreatedAt], [ModifiedAt], [CutoffMode], [CutoffDate], [DocKeyLabel], [SelectionStrategy], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql]) VALUES (N'RF_LOG2', N'KArchiveManager - System log history', 1, 1, 540, 1440, NULL, 4000, 20, 0, 1, NULL, 10000, N'LOW', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000', 0, '2024-01-01T00:00:00.000', N'ROWID', N'TIMESTAMP', N'NONE', 1, 4000, NULL, N'DocCreatedAt, Key1');
INSERT arch.Process ([ProcessCode], [Description], [IsEnabled], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [CreatedAt], [ModifiedAt], [CutoffMode], [CutoffDate], [DocKeyLabel], [SelectionStrategy], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql]) VALUES (N'INTEGRACE_DNLOAD', N'KArchiveManager - Integrace ERP to WMS download archive', 1, 1, 540, 1440, NULL, 4000, 20, 0, 1, NULL, 10000, N'LOW', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-05-22T07:31:26.000', '2026-06-02T14:00:25.000', 0, '2024-01-01T00:00:00.000', N'ROWID', N'TIMESTAMP', N'BATCH', 1, 4000, NULL, N'DocCreatedAt, Key1');
INSERT arch.Process ([ProcessCode], [Description], [IsEnabled], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [CreatedAt], [ModifiedAt], [CutoffMode], [CutoffDate], [DocKeyLabel], [SelectionStrategy], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql]) VALUES (N'INTEGRACE_UPLOAD', N'KArchiveManager - Integrace WMS to ERP upload archive', 1, 1, 540, 1440, NULL, 4000, 250, 0, 1, NULL, 10000, N'LOW', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-05-22T07:31:26.000', '2026-06-02T13:59:54.000', 0, '2024-01-01T00:00:00.000', N'ROWID', N'TIMESTAMP', N'BATCH', 1, 4000, NULL, N'DocCreatedAt, Key1');
INSERT arch.Process ([ProcessCode], [Description], [IsEnabled], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [CreatedAt], [ModifiedAt], [CutoffMode], [CutoffDate], [DocKeyLabel], [SelectionStrategy], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql]) VALUES (N'WA_AAD_PRIJEM_OSTRY_SMOKE', N'Ostry smoke test pro WA/AAD PRIJEM. Root: t_receipt, t_tran_log(receipt). BatchRowCount=10.', 1, 1, 1, 1440, 1, 10, 50, 0, 1, NULL, 10000, N'LOW', N'dbo', N't_receipt', N'a.receipt_id', N'a.wh_id', N'CAST(a.receipt_date AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', NULL, 0, '2026-05-26T09:04:36.000', '2026-06-02T07:50:04.000', 0, NULL, N'receipt_id', N'ANCHOR', N'BATCH', 1, NULL, NULL, NULL);
INSERT arch.Process ([ProcessCode], [Description], [IsEnabled], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [CreatedAt], [ModifiedAt], [CutoffMode], [CutoffDate], [DocKeyLabel], [SelectionStrategy], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql]) VALUES (N'WA_AAD_VYDEJ_OSTRY_SMOKE', N'Ostry smoke test pro WA/AAD VYDEJ. Root: t_order, t_order_detail, t_pick_detail, t_tran_log(outbound). BatchRowCount=10.', 1, 1, 1, 1440, 1, 10, 50, 0, 1, NULL, 10000, N'LOW', N'dbo', N't_order', N'a.order_number', N'a.wh_id', N'CAST(a.order_date AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', NULL, 0, '2026-05-26T09:04:36.000', '2026-06-02T07:50:04.000', 0, NULL, N'order_number', N'ANCHOR', N'BATCH', 1, NULL, NULL, NULL);

-- ---- arch.ProcessKeySpec (9 rows) ----
INSERT arch.ProcessKeySpec ([ProcessId], [KeyOrdinal], [KeyName], [SourceExpressionSql], [SqlType], [IsRequired], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_DNLOAD'), 1, N'ROWID', N't.ROWID', N'uniqueidentifier', 1, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessKeySpec ([ProcessId], [KeyOrdinal], [KeyName], [SourceExpressionSql], [SqlType], [IsRequired], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_UPLOAD'), 1, N'ROWID', N't.ROWID', N'uniqueidentifier', 1, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessKeySpec ([ProcessId], [KeyOrdinal], [KeyName], [SourceExpressionSql], [SqlType], [IsRequired], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING'), 1, N'PO_NUM', N'a.PO_NUM', N'nvarchar(256)', 1, '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.ProcessKeySpec ([ProcessId], [KeyOrdinal], [KeyName], [SourceExpressionSql], [SqlType], [IsRequired], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RF_LOG2'), 1, N'ROWID', N't.ROWID', N'nvarchar(256)', 1, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessKeySpec ([ProcessId], [KeyOrdinal], [KeyName], [SourceExpressionSql], [SqlType], [IsRequired], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), 1, N'PACKSLIP', N'a.PACKSLIP', N'nvarchar(256)', 1, '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.ProcessKeySpec ([ProcessId], [KeyOrdinal], [KeyName], [SourceExpressionSql], [SqlType], [IsRequired], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_PRIJEM_OSTRY_SMOKE'), 1, N'receipt_id', N'a.receipt_id', N'nvarchar(30)', 1, '2026-05-28T06:44:44.000', '2026-05-28T06:48:58.000');
INSERT arch.ProcessKeySpec ([ProcessId], [KeyOrdinal], [KeyName], [SourceExpressionSql], [SqlType], [IsRequired], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_PRIJEM_OSTRY_SMOKE'), 2, N'wh_id', N'ISNULL(a.wh_id, N'''')', N'nvarchar(10)', 0, '2026-05-28T06:44:44.000', '2026-05-28T06:48:58.000');
INSERT arch.ProcessKeySpec ([ProcessId], [KeyOrdinal], [KeyName], [SourceExpressionSql], [SqlType], [IsRequired], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_VYDEJ_OSTRY_SMOKE'), 1, N'order_number', N'a.order_number', N'nvarchar(30)', 1, '2026-05-28T06:44:44.000', '2026-05-28T06:48:58.000');
INSERT arch.ProcessKeySpec ([ProcessId], [KeyOrdinal], [KeyName], [SourceExpressionSql], [SqlType], [IsRequired], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_VYDEJ_OSTRY_SMOKE'), 2, N'wh_id', N'ISNULL(a.wh_id, N'''')', N'nvarchar(10)', 0, '2026-05-28T06:44:44.000', '2026-05-28T06:48:58.000');

-- ---- arch.ObjectSpec (17 rows) ----
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_DNLOAD'), N'dbo', N'DNLOAD_ARCHIVE', 10, 1, N'CAST(COALESCE(CONVERT(datetime2(3), t.date_archived), TRY_CONVERT(datetime2(3), STUFF(STUFF(STUFF(REPLACE(NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(25), t.TIMESTMP))), N''''), N''/'', N''.''), 9, 0, N''T''), 7, 0, N''-''), 5, 0, N''-''), 126)) AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.ROWID = CONVERT(uniqueidentifier, k.Key1)', N'(t.date_archived IS NOT NULL OR TRY_CONVERT(datetime2(3), STUFF(STUFF(STUFF(REPLACE(NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(25), t.TIMESTMP))), N''''), N''/'', N''.''), 9, 0, N''T''), 7, 0, N''-''), 5, 0, N''-''), 126) IS NOT NULL)', N'{SourceDb}', NULL, 1, N'ROWID');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_UPLOAD'), N'dbo', N'UPLOADARCHIVE', 10, 1, N'CAST(TRY_CONVERT(datetime2(3), STUFF(STUFF(STUFF(REPLACE(NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(25), t.TIMESTMP))), N''''), N''/'', N''.''), 9, 0, N''T''), 7, 0, N''-''), 5, 0, N''-''), 126) AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.ROWID = CONVERT(uniqueidentifier, k.Key1)', N'(t.TIMESTMP IS NOT NULL AND TRY_CONVERT(datetime2(3), STUFF(STUFF(STUFF(REPLACE(NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(25), t.TIMESTMP))), N''''), N''/'', N''.''), 9, 0, N''T''), 7, 0, N''-''), 5, 0, N''-''), 126) IS NOT NULL)', N'{SourceDb}', NULL, 1, N'ROWID');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING'), N'dbo', N'BACKRD', 10, 1, N'CAST(DATE_CREAT AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.PO_NUM = k.Key1', NULL, N'{SourceDb}', NULL, 1, N'PO_NUM');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING'), N'dbo', N'BACKRH', 20, 1, N'CAST(DATE_CREAT AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.PO_NUM = k.Key1', NULL, N'{SourceDb}', NULL, 1, N'PO_NUM');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RF_LOG2'), N'dbo', N'RF_LOG2', 10, 1, N'TRY_CONVERT(datetime2, t.DATE_TIME) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.ROWID = k.Key1', N't.DATE_TIME IS NOT NULL', N'{SourceDb}', NULL, 1, N'ROWID');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), N'dbo', N'SHIPDETL', 10, 1, N'CAST(DATECREATE AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.PACKSLIP = k.Key1', NULL, N'{SourceDb}', NULL, 1, N'PACKSLIP');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), N'dbo', N'SHIPDETL2', 20, 1, N'CAST(DATECREATE AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.PACKSLIP = k.Key1', NULL, N'{SourceDb}', NULL, 1, N'PACKSLIP');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), N'dbo', N'SHIPMSTR', 30, 1, N'CAST(COALESCE(DATE_SHIP, DATECREATE) AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.PACKSLIP = k.Key1', NULL, N'{SourceDb}', NULL, 1, N'PACKSLIP');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), N'dbo', N'SHIPLINE', 40, 1, N'CAST(BILLEDDATE AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.PACKSLIP = k.Key1', NULL, N'{SourceDb}', NULL, 1, N'PACKSLIP');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), N'dbo', N'SHIPLINE2', 50, 1, N'CAST(BILLEDDATE AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.PACKSLIP = k.Key1', NULL, N'{SourceDb}', NULL, 1, N'PACKSLIP');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), N'dbo', N'SHIPHIST', 60, 1, N'CAST(COALESCE(DATE_UPLD, DATE_SHIP, DATE_CREAT) AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', N't.PACKSLIP = k.Key1', NULL, N'{SourceDb}', NULL, 1, N'PACKSLIP');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_PRIJEM_OSTRY_SMOKE'), N'dbo', N't_receipt', 10, 1, NULL, N'CONVERT(nvarchar(256), t.receipt_id) = k.Key1 AND ISNULL(CONVERT(nvarchar(256), t.wh_id), N'''') = k.Key2', NULL, N'WA_AAD_SMOKE', N't_receipt_PRIJEM_SMOKE', 1, N'receipt_id');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_PRIJEM_OSTRY_SMOKE'), N'dbo', N't_tran_log', 20, 1, NULL, N'CONVERT(nvarchar(256), t.receipt_id) = k.Key1 AND ISNULL(CONVERT(nvarchar(256), t.wh_id), N'''') = k.Key2', NULL, N'WA_AAD_SMOKE', N'WA_AAD_SMOKE_AUDIT', 1, N'receipt_id');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_VYDEJ_OSTRY_SMOKE'), N'dbo', N't_order', 10, 1, NULL, N'CONVERT(nvarchar(256), t.order_number) = k.Key1 AND ISNULL(CONVERT(nvarchar(256), t.wh_id), N'''') = k.Key2', NULL, N'WA_AAD_SMOKE', N't_order_VYDEJ_SMOKE', 1, N'order_number');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_VYDEJ_OSTRY_SMOKE'), N'dbo', N't_order_detail', 20, 1, NULL, N'CONVERT(nvarchar(256), t.order_number) = k.Key1 AND ISNULL(CONVERT(nvarchar(256), t.wh_id), N'''') = k.Key2', NULL, N'WA_AAD_SMOKE', N't_order_detail_VYDEJ_SMOKE', 1, N'order_number');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_VYDEJ_OSTRY_SMOKE'), N'dbo', N't_pick_detail', 30, 1, NULL, N'CONVERT(nvarchar(256), t.order_number) = k.Key1 AND ISNULL(CONVERT(nvarchar(256), t.wh_id), N'''') = k.Key2', NULL, N'WA_AAD_SMOKE', N't_pick_detail_VYDEJ_SMOKE', 1, N'order_number');
INSERT arch.ObjectSpec ([ProcessId], [SourceSchema], [SourceTable], [DeleteOrder], [DeleteMode], [TimestampExpr], [JoinToAnchorPredicateSql], [AdditionalWhereSql], [ArchiveSchema], [ArchiveTable], [RequireArchiveForDelete], [NaturalKeyLabel]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_VYDEJ_OSTRY_SMOKE'), N'dbo', N't_tran_log', 40, 1, NULL, N'CONVERT(nvarchar(256), t.outbound_order_number) = k.Key1 AND ISNULL(CONVERT(nvarchar(256), t.wh_id), N'''') = k.Key2', NULL, N'WA_AAD_SMOKE', N't_tran_log_VYDEJ_SMOKE', 1, N'order_number');

-- ---- arch.ProcessDatabase (17 rows) ----
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_DNLOAD'), N'Edge', N'kArchiveManagerBackups', 0, 1040, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-28T06:44:44.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_DNLOAD'), N'KMWE_Test', N'kArchiveManagerBackups', 1, 3040, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_DNLOAD'), N'KMWEBV', N'kArchiveManagerBackups', 1, 2040, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_UPLOAD'), N'Edge', N'kArchiveManagerBackups', 1, 1050, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_UPLOAD'), N'KMWE_Test', N'kArchiveManagerBackups', 1, 3050, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_UPLOAD'), N'KMWEBV', N'kArchiveManagerBackups', 1, 2050, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING'), N'Edge', N'kArchiveManagerBackups', 1, 1010, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING'), N'KMWE_Test', N'kArchiveManagerBackups', 1, 3010, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING'), N'KMWEBV', N'kArchiveManagerBackups', 1, 2010, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:25.000', '2026-05-29T08:41:46.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RF_LOG2'), N'Edge', N'kArchiveManagerBackups', 1, 1030, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-28T06:48:58.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RF_LOG2'), N'KMWE_Test', N'kArchiveManagerBackups', 1, 3030, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-28T06:48:58.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RF_LOG2'), N'KMWEBV', N'kArchiveManagerBackups', 1, 2030, 1, 540, 1440, 0, '2024-01-01T00:00:00.000', NULL, 4000, 20, 0, 1, NULL, 10000, N'LOW', NULL, NULL, NULL, NULL, NULL, NULL, 0, N'ROWID', N'ROW', 1, 4000, NULL, N'DocCreatedAt, Key1', '2026-05-22T07:31:26.000', '2026-06-02T14:53:32.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), N'Edge', N'kArchiveManagerBackups', 1, 1020, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), N'KMWE_Test', N'kArchiveManagerBackups', 1, 3020, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), N'KMWEBV', N'kArchiveManagerBackups', 1, 2020, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:31:25.000', '2026-05-28T06:48:58.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_PRIJEM_OSTRY_SMOKE'), N'AAD', N'kArchiveManagerBackups', 1, 4010, 1, 1, 1440, 0, NULL, 1, 1, 50, 0, 1, NULL, 10000, N'LOW', N'dbo', N't_receipt', N'a.receipt_id', N'a.wh_id', N'CAST(a.receipt_date AS datetime2) AT TIME ZONE N''Central European Standard Time'' AT TIME ZONE N''UTC''', NULL, 0, N'receipt_id', NULL, 1, NULL, NULL, NULL, '2026-05-26T12:09:35.000', '2026-06-05T09:00:40.000');
INSERT arch.ProcessDatabase ([ProcessId], [SourceDb], [ArchiveDb], [IsEnabled], [RunOrder], [Mode], [RetentionDays], [CutoffSafetyLagMinutes], [CutoffMode], [CutoffDate], [BatchDocCount], [BatchRowCount], [MaxBatchesPerRun], [DelayMsBetweenBatches], [UseAppLock], [AppLockResource], [LockTimeoutMs], [DeadlockPriority], [AnchorSchema], [AnchorTable], [AnchorDocKeyExpr], [AnchorDocKey2Expr], [AnchorTimestampExpr], [AnchorExtraWhereSql], [AllowDeleteWithoutArchive], [DocKeyLabel], [AuditLevel], [RequireSupportingIndex], [MaxRowsPerTransaction], [CandidateWhereSql], [CandidateOrderSql], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'WA_AAD_VYDEJ_OSTRY_SMOKE'), N'AAD', N'kArchiveManagerBackups', 1, 4020, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-26T12:09:35.000', '2026-05-26T12:09:43.000');

-- ---- arch.IndexRequirement (16 rows) ----
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_DNLOAD'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_DNLOAD') AND SourceSchema=N'dbo' AND SourceTable=N'DNLOAD_ARCHIVE'), N'SELECTION', N'dbo', N'DNLOAD_ARCHIVE', N'date_archived,ROWID', NULL, NULL, 0, N'DNLOAD primary cutoff uses date_archived; TIMESTMP parsing is the fallback for NULL date_archived values.', '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_DNLOAD'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_DNLOAD') AND SourceSchema=N'dbo' AND SourceTable=N'DNLOAD_ARCHIVE'), N'JOIN', N'dbo', N'DNLOAD_ARCHIVE', N'ROWID', NULL, NULL, 1, N'DNLOAD timestamp keyset deletes join back by ROWID.', '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_UPLOAD'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_UPLOAD') AND SourceSchema=N'dbo' AND SourceTable=N'UPLOADARCHIVE'), N'SELECTION', N'dbo', N'UPLOADARCHIVE', N'TIMESTMP,ROWID', NULL, NULL, 0, N'UPLOAD cutoff parses TIMESTMP; for production prefer a persisted computed datetime column and an index over it plus ROWID.', '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_UPLOAD'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'INTEGRACE_UPLOAD') AND SourceSchema=N'dbo' AND SourceTable=N'UPLOADARCHIVE'), N'JOIN', N'dbo', N'UPLOADARCHIVE', N'ROWID', NULL, NULL, 1, N'UPLOAD timestamp keyset deletes join back by ROWID.', '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING') AND SourceSchema=N'dbo' AND SourceTable=N'BACKRH'), N'SELECTION', N'dbo', N'BACKRH', N'DATE_CREAT,PO_NUM', NULL, NULL, 1, N'Anchor selection for RECEIVING.', '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING') AND SourceSchema=N'dbo' AND SourceTable=N'BACKRD'), N'JOIN', N'dbo', N'BACKRD', N'PO_NUM', NULL, NULL, 1, N'Child join to prepared keyset.', '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RECEIVING') AND SourceSchema=N'dbo' AND SourceTable=N'BACKRH'), N'JOIN', N'dbo', N'BACKRH', N'PO_NUM', NULL, NULL, 1, N'Header join to prepared keyset.', '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RF_LOG2'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RF_LOG2') AND SourceSchema=N'dbo' AND SourceTable=N'RF_LOG2'), N'SELECTION', N'dbo', N'RF_LOG2', N'DATE_TIME,ROWID', NULL, N'DATE_TIME IS NOT NULL', 1, N'RF_LOG2 timestamp keyset selection uses DATE_TIME and must be backed by an index.', '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RF_LOG2'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'RF_LOG2') AND SourceSchema=N'dbo' AND SourceTable=N'RF_LOG2'), N'JOIN', N'dbo', N'RF_LOG2', N'ROWID', NULL, NULL, 1, N'Timestamp keyset deletes join back by ROWID.', '2026-05-22T07:31:26.000', '2026-05-22T07:31:26.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING') AND SourceSchema=N'dbo' AND SourceTable=N'SHIPHIST'), N'SELECTION', N'dbo', N'SHIPHIST', N'DATE_UPLD,PACKSLIP', NULL, NULL, 1, N'Anchor selection for SHIPPING. If COALESCE is not sargable, use a persisted computed cutoff column.', '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING') AND SourceSchema=N'dbo' AND SourceTable=N'SHIPDETL'), N'JOIN', N'dbo', N'SHIPDETL', N'PACKSLIP', NULL, NULL, 1, N'Child join to prepared keyset.', '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING') AND SourceSchema=N'dbo' AND SourceTable=N'SHIPDETL2'), N'JOIN', N'dbo', N'SHIPDETL2', N'PACKSLIP', NULL, NULL, 1, N'Child join to prepared keyset.', '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING') AND SourceSchema=N'dbo' AND SourceTable=N'SHIPMSTR'), N'JOIN', N'dbo', N'SHIPMSTR', N'PACKSLIP', NULL, NULL, 1, N'Child join to prepared keyset.', '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING') AND SourceSchema=N'dbo' AND SourceTable=N'SHIPLINE'), N'JOIN', N'dbo', N'SHIPLINE', N'PACKSLIP', NULL, NULL, 1, N'Child join to prepared keyset.', '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING') AND SourceSchema=N'dbo' AND SourceTable=N'SHIPLINE2'), N'JOIN', N'dbo', N'SHIPLINE2', N'PACKSLIP', NULL, NULL, 1, N'Child join to prepared keyset.', '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');
INSERT arch.IndexRequirement ([ProcessId], [ObjectSpecId], [RequirementType], [SourceSchema], [SourceTable], [KeyColumnsCsv], [IncludeColumnsCsv], [FilterSql], [IsMandatory], [Notes], [CreatedAt], [ModifiedAt]) VALUES ((SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING'), (SELECT ObjectSpecId FROM arch.ObjectSpec WHERE ProcessId=(SELECT ProcessId FROM arch.Process WHERE ProcessCode=N'SHIPPING') AND SourceSchema=N'dbo' AND SourceTable=N'SHIPHIST'), N'JOIN', N'dbo', N'SHIPHIST', N'PACKSLIP', NULL, NULL, 1, N'Header join to prepared keyset.', '2026-05-22T07:31:25.000', '2026-05-22T07:31:25.000');

-- ---- arch.RunProfile (14 rows) ----
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'EDGE_ALL_20M', N'Manual/concurrent run: all enabled processes for Edge.', 1, 0, 100, NULL, N'Edge', NULL, 20, 0, NULL, 60, '2026-05-22T07:31:25.000', '2026-05-22T07:31:26.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'INTEGRACE_DNLOAD_KMWEBV', NULL, 1, 0, 100, N'INTEGRACE_DNLOAD', N'KMWEBV', NULL, 25, 0, NULL, 60, '2026-05-28T12:38:49.000', '2026-05-28T12:38:49.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'INTEGRACE_UPLOAD_EDGE', NULL, 1, 0, 100, N'INTEGRACE_UPLOAD', N'Edge', NULL, 25, 0, NULL, 60, '2026-05-28T12:38:49.000', '2026-05-28T12:38:49.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'JOB_DEFAULT', N'Default scheduled run for all enabled ProcessDatabase mappings.', 1, 1, 10, NULL, NULL, NULL, 55, 0, NULL, 60, '2026-05-22T07:31:25.000', '2026-05-22T07:31:26.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'KMWE_TEST_ALL_20M', N'Manual/concurrent run: all enabled processes for KMWE_Test.', 1, 0, 120, NULL, N'KMWE_Test', NULL, 20, 0, NULL, 60, '2026-05-22T07:31:25.000', '2026-05-22T07:31:26.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'KMWEBV_ALL_20M', N'Manual/concurrent run: all enabled processes for KMWEBV.', 1, 0, 110, NULL, N'KMWEBV', NULL, 20, 0, NULL, 60, '2026-05-22T07:31:25.000', '2026-05-22T07:31:26.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'RECEIVING_ALL_20M', N'Manual run: RECEIVING process across all enabled source DBs.', 1, 0, 200, N'RECEIVING', NULL, NULL, 20, 0, NULL, 60, '2026-05-22T07:31:25.000', '2026-05-22T07:31:26.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'RECEIVING_KMWEBV', N'Manual run: RECEIVING process for KMWEBV source database.', 1, 0, 320, N'RECEIVING', N'KMWEBV', NULL, 120, 0, NULL, 60, '2026-05-28T12:15:37.000', '2026-05-28T12:15:37.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'RF_LOG2_EDGE', NULL, 1, 0, 100, N'RF_LOG2', N'Edge', NULL, 25, 0, NULL, 60, '2026-05-28T13:01:30.000', '2026-05-28T13:01:30.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'RF_LOG2_KMWE_TEST', NULL, 1, 0, 100, N'RF_LOG2', N'KMWE_Test', NULL, 25, 0, NULL, 60, '2026-05-28T12:38:49.000', '2026-05-28T12:38:49.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'SHIPPING_ALL_20M', N'Manual run: SHIPPING process across all enabled source DBs.', 1, 0, 210, N'SHIPPING', NULL, NULL, 20, 0, NULL, 60, '2026-05-28T12:13:07.000', '2026-05-28T12:13:07.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'SHIPPING_KMWEBV', N'Manual run: SHIPPING process for KMWEBV source database.', 1, 0, 310, N'SHIPPING', N'KMWEBV', NULL, 20, 0, NULL, 60, '2026-05-28T12:15:37.000', '2026-05-28T12:15:37.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'WA_AAD_PRIJEM_OSTRY_SMOKE_AAD', NULL, 1, 0, 100, N'WA_AAD_PRIJEM_OSTRY_SMOKE', N'AAD', NULL, 25, 0, NULL, 60, '2026-05-28T13:40:46.000', '2026-05-28T13:40:46.000');
INSERT arch.RunProfile ([RunProfileCode], [Description], [IsEnabled], [RunOnSchedule], [RunOrder], [ProcessCodeFilter], [SourceDbFilter], [ArchiveDbFilter], [RunWindowMinutes], [DryRun], [MaxCandidates], [PausedCooldownSeconds], [CreatedAt], [ModifiedAt]) VALUES (N'WA_AAD_VYDEJ_OSTRY_SMOKE_AAD', NULL, 1, 0, 100, N'WA_AAD_VYDEJ_OSTRY_SMOKE', N'AAD', NULL, 25, 0, NULL, 60, '2026-05-28T13:40:46.000', '2026-05-28T13:40:46.000');

COMMIT;
GO
PRINT 'Seed complete. Counts:';
SELECT 'Process' t,COUNT(*) n FROM arch.Process UNION ALL SELECT 'ProcessDatabase',COUNT(*) FROM arch.ProcessDatabase UNION ALL SELECT 'ObjectSpec',COUNT(*) FROM arch.ObjectSpec UNION ALL SELECT 'ProcessKeySpec',COUNT(*) FROM arch.ProcessKeySpec UNION ALL SELECT 'IndexRequirement',COUNT(*) FROM arch.IndexRequirement UNION ALL SELECT 'RunProfile',COUNT(*) FROM arch.RunProfile;
GO
EXEC arch.usp_ValidateConfiguration;
GO
